/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("/chambre_baked_final.gltf");
  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, -1, 0]}
      position={[6, -3, -10]}
    >
      <group scale={4.588}>
        <group
          position={[0.828, 0.059, -0.856]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_4_1.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_4_2.geometry}
            material={materials.Brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_4_3.geometry}
            material={materials.Plant_Green}
          />
        </group>
      </group>
      <group
        position={[-2.466, 0.24, -2.226]}
        rotation={[-Math.PI, 0.039, -Math.PI]}
        scale={5.711}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.drawer_1.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.drawer_1_1.geometry}
          material={materials.metal}
        />
      </group>
      <group
        position={[1.471, 0.848, -3.992]}
        rotation={[-Math.PI, 1.523, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh144173986.geometry}
          material={materials.mat23}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh144173986_1.geometry}
          material={materials.mat15}
        />
      </group>
      <group position={[-0.484, 2.469, -3.335]} scale={0.401}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh485226736.geometry}
          material={materials.mat16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh485226736_1.geometry}
          material={materials["mat23.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh485226736_2.geometry}
          material={materials.mat17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh485226736_3.geometry}
          material={materials["mat15.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh485226736_4.geometry}
          material={materials.mat25}
        />
      </group>
      <group position={[1.847, 2.243, -4.412]} scale={[1.291, 0.447, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.StandingDesk1.geometry}
          material={materials.MetalStandingDesk1}
          position={[-0.3, 0, 0.404]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
      <group
        position={[1.092, 2.499, -4.04]}
        rotation={[Math.PI, -0.839, Math.PI]}
        scale={0.026}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iMac_1.geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iMac_1_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group
        position={[-0.346, 0.832, -1.403]}
        rotation={[Math.PI, -0.076, Math.PI]}
        scale={1.219}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh646429156.geometry}
          material={materials["mat16.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh646429156_1.geometry}
          material={materials.mat11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh646429156_2.geometry}
          material={materials["mat15.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh646429156_3.geometry}
          material={materials["mat23.002"]}
        />
      </group>
      <group
        position={[1.469, 2.156, -3.844]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.82}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430.geometry}
          material={materials["mat23.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430_1.geometry}
          material={materials.mat20}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430_2.geometry}
          material={materials.mat22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430_3.geometry}
          material={materials.mat24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430_4.geometry}
          material={materials.mat10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430_5.geometry}
          material={materials.mat5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430_6.geometry}
          material={materials.mat8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh1447727430_7.geometry}
          material={materials.mat12}
        />
      </group>
      <group position={[0.74, 1.531, -3.802]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh"].geometry}
          material={materials["mat5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh_1"].geometry}
          material={materials.mat21}
        />
      </group>
      <group position={[0.877, 1.531, -3.802]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh001"].geometry}
          material={materials["mat5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh001_1"].geometry}
          material={materials.mat21}
        />
      </group>
      <group position={[1.026, 1.531, -3.802]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh002"].geometry}
          material={materials["mat5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh002_1"].geometry}
          material={materials.mat21}
        />
      </group>
      <group
        position={[1.238, 1.531, -3.802]}
        rotation={[Math.PI / 2, -1.357, Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh003"].geometry}
          material={materials["mat5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh003_1"].geometry}
          material={materials.mat21}
        />
      </group>
      <group scale={3.533}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials.Default}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[-4.425, 3.554, 3.227]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-1, -1.804, -0.129]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cadreTyler_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cadreTyler_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[0.695, 0.677, -3.985]}
        rotation={[Math.PI / 2, 0.133, -Math.PI / 2]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album_1.geometry}
          material={materials.kendrick}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album_2.geometry}
          material={materials.kendrick_back}
        />
      </group>
      <group
        position={[0.822, 0.678, -4.026]}
        rotation={[1.58, 0.233, -1.559]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album001_1.geometry}
          material={materials.paramore}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album001_2.geometry}
          material={materials.paramore_back}
        />
      </group>
      <group
        position={[0.885, 0.691, -3.813]}
        rotation={[1.58, 0.131, -1.558]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album002_1.geometry}
          material={materials.clammbon}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album002_2.geometry}
          material={materials.clammbon_back}
        />
      </group>
      <group
        position={[0.766, 0.689, -3.985]}
        rotation={[1.58, 0.217, -1.558]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album003_1.geometry}
          material={materials.tigran}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album003_2.geometry}
          material={materials.tigran_back}
        />
      </group>
      <group
        position={[0.865, 0.688, -3.826]}
        rotation={[1.58, 0.131, -1.558]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album004_1.geometry}
          material={materials.bach}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album004_2.geometry}
          material={materials.bach_back}
        />
      </group>
      <group
        position={[0.924, 0.703, -3.841]}
        rotation={[1.58, 0.131, -1.558]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album005_1.geometry}
          material={materials.thundercat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album005_2.geometry}
          material={materials.thundercat_back}
        />
      </group>
      <group
        position={[0.982, 0.703, -3.89]}
        rotation={[1.58, 0.131, -1.558]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album006_1.geometry}
          material={materials.nerd}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album006_2.geometry}
          material={materials.nerd_back}
        />
      </group>
      <group
        position={[1.02, 0.705, -3.911]}
        rotation={[1.58, 0.131, -1.558]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album007_1.geometry}
          material={materials.dangelo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album007_2.geometry}
          material={materials.dangelo_back}
        />
      </group>
      <group
        position={[1.166, 0.705, -4.015]}
        rotation={[1.58, 0.131, -1.558]}
        scale={[0.691, 0.222, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album008_1.geometry}
          material={materials.naia}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.album008_2.geometry}
          material={materials.naia_back}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cadreCeleste.geometry}
        material={materials["Material.002"]}
        position={[-2.929, 4.324, -4.373]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, -1.023, -0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.celeste.geometry}
        material={materials.celeste}
        position={[-2.929, 4.324, -4.373]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, -1.023, -0.129]}
      />
    </group>
  );
}

useGLTF.preload("/chambre_baked_final.gltf");
